# Generated by Django 3.2.16 on 2022-12-05 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import sharinglogic.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingUser',
            fields=[
                ('id', sharinglogic.models.UuidPKField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255)),
                ('timing', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('trip_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('isToAirport', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Sharing User',
                'verbose_name_plural': 'Sharing Users',
                'db_table': 'sharing_user',
                'ordering': ['name'],
            },
        ),
    ]
